/* The following code was generated by JFlex 1.6.1 */

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintStream;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>PCAT.flex</tt>
 */
public class PCATScanner extends Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\0\1\12"+
    "\5\0\1\4\1\6\1\5\1\56\1\44\1\57\1\11\1\60\12\10"+
    "\1\45\1\46\1\54\1\53\1\55\2\0\1\16\1\23\1\40\1\20"+
    "\1\24\1\33\1\25\1\42\1\26\2\7\1\31\1\37\1\17\1\30"+
    "\1\36\1\7\1\21\1\32\1\35\1\41\1\27\1\43\1\34\1\22"+
    "\1\7\1\47\1\15\1\50\1\0\1\61\1\0\15\7\1\14\5\7"+
    "\1\14\6\7\1\51\1\13\1\52\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff92\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\17\6\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\1\1\27\1\30\1\31\2\0\1\11\1\32\1\11"+
    "\4\6\1\33\1\6\1\34\4\6\1\35\1\36\1\6"+
    "\1\37\1\40\3\6\1\41\5\6\1\42\1\43\1\44"+
    "\1\45\1\27\2\0\1\46\1\0\1\47\1\6\1\50"+
    "\1\51\4\6\1\52\2\6\1\53\1\6\1\54\3\6"+
    "\1\55\2\6\1\0\1\6\1\56\3\6\1\57\1\60"+
    "\1\61\1\62\1\63\4\6\1\64\2\6\1\65\3\6"+
    "\1\66\1\67\1\70\1\71\1\72\2\6\1\73\2\6"+
    "\1\74";

  private static int [] zzUnpackAction() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\62\0\226\0\310\0\62\0\372"+
    "\0\u012c\0\62\0\u015e\0\u0190\0\u01c2\0\u01f4\0\u0226\0\u0258"+
    "\0\u028a\0\u02bc\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6\0\u03e8"+
    "\0\u041a\0\u044c\0\62\0\u047e\0\62\0\62\0\62\0\62"+
    "\0\62\0\62\0\u04b0\0\u04e2\0\62\0\62\0\62\0\u0514"+
    "\0\u0546\0\62\0\u0514\0\u0578\0\u05aa\0\u05dc\0\u060e\0\u0640"+
    "\0\u0672\0\u06a4\0\u06d6\0\u0708\0\372\0\u073a\0\372\0\u076c"+
    "\0\u079e\0\u07d0\0\u0802\0\372\0\372\0\u0834\0\372\0\372"+
    "\0\u0866\0\u0898\0\u08ca\0\372\0\u08fc\0\u092e\0\u0960\0\u0992"+
    "\0\u09c4\0\62\0\62\0\62\0\62\0\u09f6\0\u0a28\0\u0a5a"+
    "\0\u0578\0\u060e\0\372\0\u0a8c\0\372\0\372\0\u0abe\0\u0af0"+
    "\0\u0b22\0\u0b54\0\372\0\u0b86\0\u0bb8\0\372\0\u0bea\0\372"+
    "\0\u0c1c\0\u0c4e\0\u0c80\0\372\0\u0cb2\0\u0ce4\0\u0d16\0\u0d48"+
    "\0\372\0\u0d7a\0\u0dac\0\u0dde\0\u0e10\0\372\0\372\0\372"+
    "\0\372\0\u0e42\0\u0e74\0\u0ea6\0\u0ed8\0\372\0\u0f0a\0\u0f3c"+
    "\0\372\0\u0f6e\0\u0fa0\0\u0fd2\0\372\0\372\0\372\0\372"+
    "\0\372\0\u1004\0\u1036\0\372\0\u1068\0\u109a\0\372";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\2\1\10\1\2\1\14\1\15\1\16"+
    "\1\17\1\10\1\20\1\21\1\10\1\22\1\23\1\24"+
    "\1\25\1\10\1\26\1\10\1\27\1\30\1\31\3\10"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\64\0"+
    "\1\4\64\0\1\51\62\0\1\52\62\0\2\10\3\0"+
    "\1\10\1\0\26\10\25\0\1\53\1\11\1\54\2\0"+
    "\1\53\1\0\26\53\16\0\2\13\1\55\1\13\1\56"+
    "\1\13\1\56\3\13\1\57\2\56\1\60\44\13\7\0"+
    "\2\10\3\0\1\10\1\0\1\10\1\61\1\10\1\62"+
    "\22\10\25\0\2\10\3\0\1\10\1\0\12\10\1\63"+
    "\13\10\25\0\2\10\3\0\1\10\1\0\10\10\1\64"+
    "\1\10\1\65\13\10\25\0\2\10\3\0\1\10\1\0"+
    "\6\10\1\66\17\10\25\0\2\10\3\0\1\10\1\0"+
    "\4\10\1\67\1\10\1\70\17\10\25\0\2\10\3\0"+
    "\1\10\1\0\1\10\1\71\11\10\1\72\2\10\1\73"+
    "\7\10\25\0\2\10\3\0\1\10\1\0\14\10\1\74"+
    "\1\75\10\10\25\0\2\10\3\0\1\10\1\0\1\76"+
    "\25\10\25\0\2\10\3\0\1\10\1\0\3\10\1\77"+
    "\11\10\1\100\10\10\25\0\2\10\3\0\1\10\1\0"+
    "\12\10\1\101\13\10\25\0\2\10\3\0\1\10\1\0"+
    "\12\10\1\102\13\10\25\0\2\10\3\0\1\10\1\0"+
    "\4\10\1\103\5\10\1\104\11\10\1\105\1\10\25\0"+
    "\2\10\3\0\1\10\1\0\3\10\1\106\22\10\25\0"+
    "\2\10\3\0\1\10\1\0\12\10\1\107\13\10\25\0"+
    "\2\10\3\0\1\10\1\0\3\10\1\110\20\10\1\111"+
    "\1\10\71\0\1\112\61\0\1\113\1\0\1\114\57\0"+
    "\1\115\15\0\2\53\3\0\1\53\1\0\26\53\16\0"+
    "\5\116\1\117\1\120\53\116\10\0\1\121\51\0\4\55"+
    "\1\0\1\55\1\0\3\55\1\57\2\0\1\122\44\55"+
    "\2\56\1\0\7\56\1\0\47\56\12\0\1\57\2\0"+
    "\1\122\44\0\2\56\1\0\7\56\1\57\2\56\1\60"+
    "\44\56\7\0\2\10\3\0\1\10\1\0\2\10\1\123"+
    "\23\10\25\0\2\10\3\0\1\10\1\0\3\10\1\124"+
    "\22\10\25\0\2\10\3\0\1\10\1\0\17\10\1\125"+
    "\6\10\25\0\2\10\3\0\1\10\1\0\11\10\1\126"+
    "\14\10\25\0\2\10\3\0\1\10\1\0\1\127\16\10"+
    "\1\130\2\10\1\131\3\10\25\0\2\10\3\0\1\10"+
    "\1\0\7\10\1\132\16\10\25\0\2\10\3\0\1\10"+
    "\1\0\2\10\1\133\23\10\25\0\2\10\3\0\1\10"+
    "\1\0\14\10\1\134\11\10\25\0\2\10\3\0\1\10"+
    "\1\0\10\10\1\135\15\10\25\0\2\10\3\0\1\10"+
    "\1\0\3\10\1\136\22\10\25\0\2\10\3\0\1\10"+
    "\1\0\12\10\1\137\13\10\25\0\2\10\3\0\1\10"+
    "\1\0\3\10\1\140\22\10\25\0\2\10\3\0\1\10"+
    "\1\0\20\10\1\141\5\10\25\0\2\10\3\0\1\10"+
    "\1\0\6\10\1\142\17\10\25\0\2\10\3\0\1\10"+
    "\1\0\12\10\1\143\13\10\25\0\2\10\3\0\1\10"+
    "\1\0\2\10\1\144\23\10\25\0\2\10\3\0\1\10"+
    "\1\0\10\10\1\145\15\10\25\0\2\10\3\0\1\10"+
    "\1\0\10\10\1\146\15\10\16\0\5\116\1\147\1\120"+
    "\53\116\5\0\1\117\1\4\53\0\5\120\1\147\54\120"+
    "\7\0\2\10\3\0\1\10\1\0\1\150\25\10\25\0"+
    "\2\10\3\0\1\10\1\0\2\10\1\151\23\10\25\0"+
    "\2\10\3\0\1\10\1\0\23\10\1\152\2\10\25\0"+
    "\2\10\3\0\1\10\1\0\12\10\1\153\13\10\25\0"+
    "\2\10\3\0\1\10\1\0\10\10\1\154\15\10\25\0"+
    "\2\10\3\0\1\10\1\0\6\10\1\155\17\10\25\0"+
    "\2\10\3\0\1\10\1\0\17\10\1\156\6\10\25\0"+
    "\2\10\3\0\1\10\1\0\20\10\1\157\5\10\25\0"+
    "\2\10\3\0\1\10\1\0\6\10\1\160\17\10\25\0"+
    "\2\10\3\0\1\10\1\0\1\10\1\161\24\10\25\0"+
    "\2\10\3\0\1\10\1\0\7\10\1\162\12\10\1\163"+
    "\3\10\25\0\2\10\3\0\1\10\1\0\17\10\1\164"+
    "\6\10\25\0\2\10\3\0\1\10\1\0\13\10\1\165"+
    "\12\10\16\0\5\120\1\147\1\4\53\120\7\0\2\10"+
    "\3\0\1\10\1\0\4\10\1\166\21\10\25\0\2\10"+
    "\3\0\1\10\1\0\3\10\1\167\22\10\25\0\2\10"+
    "\3\0\1\10\1\0\3\10\1\170\22\10\25\0\2\10"+
    "\3\0\1\10\1\0\1\10\1\171\24\10\25\0\2\10"+
    "\3\0\1\10\1\0\10\10\1\172\15\10\25\0\2\10"+
    "\3\0\1\10\1\0\3\10\1\173\22\10\25\0\2\10"+
    "\3\0\1\10\1\0\6\10\1\174\17\10\25\0\2\10"+
    "\3\0\1\10\1\0\6\10\1\175\17\10\25\0\2\10"+
    "\3\0\1\10\1\0\6\10\1\176\17\10\25\0\2\10"+
    "\3\0\1\10\1\0\1\10\1\177\24\10\25\0\2\10"+
    "\3\0\1\10\1\0\2\10\1\200\23\10\25\0\2\10"+
    "\3\0\1\10\1\0\15\10\1\201\10\10\25\0\2\10"+
    "\3\0\1\10\1\0\1\202\25\10\25\0\2\10\3\0"+
    "\1\10\1\0\2\10\1\203\23\10\25\0\2\10\3\0"+
    "\1\10\1\0\21\10\1\204\4\10\25\0\2\10\3\0"+
    "\1\10\1\0\23\10\1\205\2\10\25\0\2\10\3\0"+
    "\1\10\1\0\3\10\1\206\22\10\25\0\2\10\3\0"+
    "\1\10\1\0\6\10\1\207\17\10\16\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4300];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\2\1\1\11\2\1\1\11"+
    "\20\1\1\11\1\1\6\11\2\1\3\11\2\1\1\11"+
    "\1\1\2\0\34\1\4\11\1\1\2\0\1\1\1\0"+
    "\24\1\1\0\40\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	File errors= new File("Errors.txt");
	PrintStream eLog;
	
	public void printInFile(String str) throws FileNotFoundException{
		if(!errors.exists()) {
			try {
				errors.createNewFile();
			} catch (IOException e) {
				e.printStackTrace();
			}
		} 
		if(eLog==null)
			eLog= new PrintStream(errors);
		eLog.println(str);
	}
	
	public boolean isZzAtEOF() {
		return zzAtEOF;
	}
	
	public void setZzAtEOF(boolean zzAtEOF) {
		this.zzAtEOF = zzAtEOF;
	}
	
	public Yytoken token(tok_type type, String tok, int val){
		return new Yytoken(type, tok, val, yyline, yycolumn);
	}
	
	public Yytoken token(tok_type type, String tok, String val){
		return new Yytoken(type, tok, val, yyline, yycolumn);
	}
	
	public Yytoken token(tok_type type, String tok, tok_val val){
		return new Yytoken(type, tok, val, yyline, yycolumn);
	}
	
	public Yytoken token(tok_type type, Integer tok, int val){
		return new Yytoken(type, ""+tok, val, yyline, yycolumn);
	}
	
	public Yytoken token(tok_type type, String tok){
		return new Yytoken(type, tok, yyline, yycolumn);
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PCATScanner(java.io.Reader in) {
  	super();
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 164) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Yytoken yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { printInFile("Error at line "+yyline+", column "+yycolumn+": Unrecognized symbol "+yytext()+". Skipping");
            }
          case 61: break;
          case 2: 
            { /* ignore */
            }
          case 62: break;
          case 3: 
            { return token(tok_type.TOK_LP, "(");
            }
          case 63: break;
          case 4: 
            { return token(tok_type.TOK_OP_REL, "*", tok_val.OP_MUL_TIMES);
            }
          case 64: break;
          case 5: 
            { return token(tok_type.TOK_RP, ")");
            }
          case 65: break;
          case 6: 
            { if(yylength() > 10) {
							printInFile("Identifier length > 255 of identifier: "+yytext()+"\" at line "+yyline+", column "+yycolumn);
											throw new RuntimeException("Identifer "+yytext()+" exceeded 255 length at line "+yyline+", column "+yycolumn); }
						
						else{
						int value = addIdentifier(yytext());
						return token(tok_type.TOK_IDENTIFIER, yytext(), value);
						}
            }
          case 66: break;
          case 7: 
            { return token(tok_type.TOK_INTLIT, (int)(new Integer(yytext())), (int)(new Integer(yytext())));
            }
          case 67: break;
          case 8: 
            { return token(tok_type.TOK_DOT, ".");
            }
          case 68: break;
          case 9: 
            { printInFile("Error at line "+yyline+", column "+yycolumn+": "+yytext()+"...Unterminated string. Skipping");
            }
          case 69: break;
          case 10: 
            { return token(tok_type.TOK_COMMA, ",");
            }
          case 70: break;
          case 11: 
            { return token(tok_type.TOK_COLON, ":");
            }
          case 71: break;
          case 12: 
            { return token(tok_type.TOK_SEMI, ";");
            }
          case 72: break;
          case 13: 
            { return token(tok_type.TOK_LB, "[");
            }
          case 73: break;
          case 14: 
            { return token(tok_type.TOK_RB, "]");
            }
          case 74: break;
          case 15: 
            { return token(tok_type.TOK_LC, "{");
            }
          case 75: break;
          case 16: 
            { return token(tok_type.TOK_RC, "}");
            }
          case 76: break;
          case 17: 
            { return token(tok_type.TOK_OP_REL, "=", tok_val.OP_EQ);
            }
          case 77: break;
          case 18: 
            { return token(tok_type.TOK_OP_REL, "<", tok_val.OP_LT);
            }
          case 78: break;
          case 19: 
            { return token(tok_type.TOK_OP_REL, ">", tok_val.OP_GT);
            }
          case 79: break;
          case 20: 
            { return token(tok_type.TOK_OP_REL, "+", tok_val.OP_ADD_PLUS);
            }
          case 80: break;
          case 21: 
            { return token(tok_type.TOK_OP_REL, "-", tok_val.OP_ADD_MINUS);
            }
          case 81: break;
          case 22: 
            { return token(tok_type.TOK_OP_REL, "/", tok_val.OP_MUL_DIV);
            }
          case 82: break;
          case 23: 
            { printInFile("FATAL: Dangling comment \""+yytext()+"\" at line "+yyline+", column "+yycolumn);
											throw new RuntimeException("Dangling comment \""+yytext()+"\" at line "+yyline+", column "+yycolumn);
            }
          case 83: break;
          case 24: 
            { eLog.println("FATAL: Unmatched \""+yytext()+"\" at line "+yyline+", column "+yycolumn);
												throw new RuntimeException("Unmatched \""+yytext()+"\" at line "+yyline+", column "+yycolumn);
            }
          case 84: break;
          case 25: 
            { printInFile("Error at line "+yyline+", column "+yycolumn+": identifier "+yytext()+" must begin with a letter. Skipping");
            }
          case 85: break;
          case 26: 
            { return token(tok_type.TOK_STRLIT, yytext(), yytext());
            }
          case 86: break;
          case 27: 
            { return token(tok_type.TOK_DO, "DO");
            }
          case 87: break;
          case 28: 
            { return token(tok_type.TOK_BY, "BY");
            }
          case 88: break;
          case 29: 
            { return token(tok_type.TOK_IS, "IS");
            }
          case 89: break;
          case 30: 
            { return token(tok_type.TOK_IF, "IF");
            }
          case 90: break;
          case 31: 
            { return token(tok_type.TOK_OP_OR, "OR", tok_val.OP_OR);
            }
          case 91: break;
          case 32: 
            { return token(tok_type.TOK_OF, "OF");
            }
          case 92: break;
          case 33: 
            { return token(tok_type.TOK_TO, "TO");
            }
          case 93: break;
          case 34: 
            { return token(tok_type.TOK_OP_REL, ":=", tok_val.OP_ASSIGN);
            }
          case 94: break;
          case 35: 
            { return token(tok_type.TOK_OP_REL, "<=", tok_val.OP_LE);
            }
          case 95: break;
          case 36: 
            { return token(tok_type.TOK_OP_REL, "<>", tok_val.OP_NE);
            }
          case 96: break;
          case 37: 
            { return token(tok_type.TOK_OP_REL, ">=", tok_val.OP_GE);
            }
          case 97: break;
          case 38: 
            { return token(tok_type.TOK_REALLIT, yytext(), yytext());
            }
          case 98: break;
          case 39: 
            { return token(tok_type.TOK_OP_AND, "AND", tok_val.OP_AND);
            }
          case 99: break;
          case 40: 
            { return token(tok_type.TOK_OP_NOT, "NOT", tok_val.OP_NOT);
            }
          case 100: break;
          case 41: 
            { return token(tok_type.TOK_OP_TIMES, "DIV", tok_val.OP_MUL_DIV);
            }
          case 101: break;
          case 42: 
            { return token(tok_type.TOK_END, "END");
            }
          case 102: break;
          case 43: 
            { return token(tok_type.TOK_VAR, "VAR");
            }
          case 103: break;
          case 44: 
            { return token(tok_type.TOK_FOR, "FOR");
            }
          case 104: break;
          case 45: 
            { return token(tok_type.TOK_OP_TIMES, "MOD", tok_val.OP_MUL_MOD);
            }
          case 105: break;
          case 46: 
            { return token(tok_type.TOK_READ, "READ");
            }
          case 106: break;
          case 47: 
            { return token(tok_type.TOK_ELSE, "ELSE");
            }
          case 107: break;
          case 48: 
            { return token(tok_type.TOK_EXIT, "EXIT");
            }
          case 108: break;
          case 49: 
            { return token(tok_type.TOK_LOOP, "LOOP");
            }
          case 109: break;
          case 50: 
            { return token(tok_type.TOK_TYPE, "TYPE");
            }
          case 110: break;
          case 51: 
            { return token(tok_type.TOK_THEN, "THEN");
            }
          case 111: break;
          case 52: 
            { return token(tok_type.TOK_ARRAY, "ARRAY");
            }
          case 112: break;
          case 53: 
            { return token(tok_type.TOK_BEGIN, "BEGIN");
            }
          case 113: break;
          case 54: 
            { return token(tok_type.TOK_WRITE, "WRITE");
            }
          case 114: break;
          case 55: 
            { return token(tok_type.TOK_WHILE, "WHILE");
            }
          case 115: break;
          case 56: 
            { return token(tok_type.TOK_RETURN, "RETURN");
            }
          case 116: break;
          case 57: 
            { return token(tok_type.TOK_RECORD, "RECORD");
            }
          case 117: break;
          case 58: 
            { return token(tok_type.TOK_ELSEIF, "ELSEIF");
            }
          case 118: break;
          case 59: 
            { return token(tok_type.TOK_PROGRAM, "PROGRAM");
            }
          case 119: break;
          case 60: 
            { return token(tok_type.TOK_PROCEDURE, "PROCEDURE");
            }
          case 120: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
